/*

/**
 *
 * @author Dewberry
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package snake;

import java.awt.CardLayout;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.event.MouseMotionAdapter;
import javax.swing.ImageIcon;

public class MainMenu extends javax.swing.JFrame {
    
    private ImageIcon iconStartH;
    private ImageIcon iconStart;
    private ImageIcon iconExit;
    private ImageIcon iconExitH;
    private ImageIcon iconMinimize;
    private ImageIcon iconMinimizeH;
    private ImageIcon iconDifficulty;
    private ImageIcon iconDifficultyH;
    
    
    private int dragXPos, dragYPos;
    SnakeBoard snakeBoard;
    CardLayout cardLayout;
    
    /**
     * Creates new form MainMenu
     */
    public MainMenu() {
        dragXPos = dragYPos = -1;
        initComponents();
        
                //load
        loadImages();
        loadListeners();
        
        
        //Panels
        cardLayout = (CardLayout) panelWindows.getLayout();
        snakeBoard = new SnakeBoard();
        panelWindows.add(snakeBoard, "card3");
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dragPanel = new javax.swing.JPanel();
        dragBox = new javax.swing.JPanel();
        btnMinimize = new javax.swing.JLabel();
        btnExit = new javax.swing.JLabel();
        panelWindows = new javax.swing.JPanel();
        PanelStart = new javax.swing.JPanel();
        lblHighScore = new javax.swing.JLabel();
        title = new javax.swing.JLabel();
        btnStart = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(960, 596));
        setMinimumSize(new java.awt.Dimension(960, 596));
        setUndecorated(true);
        setResizable(false);
        setSize(new java.awt.Dimension(960, 596));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        dragPanel.setBackground(new java.awt.Color(0, 153, 153));
        dragPanel.setMaximumSize(new java.awt.Dimension(960, 36));
        dragPanel.setMinimumSize(new java.awt.Dimension(960, 36));

        dragBox.setBackground(new java.awt.Color(51, 204, 0));
        dragBox.setOpaque(false);

        javax.swing.GroupLayout dragBoxLayout = new javax.swing.GroupLayout(dragBox);
        dragBox.setLayout(dragBoxLayout);
        dragBoxLayout.setHorizontalGroup(
            dragBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 820, Short.MAX_VALUE)
        );
        dragBoxLayout.setVerticalGroup(
            dragBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        btnMinimize.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/iconMinimize.png"))); // NOI18N
        btnMinimize.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        btnExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/iconExit.png"))); // NOI18N
        btnExit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout dragPanelLayout = new javax.swing.GroupLayout(dragPanel);
        dragPanel.setLayout(dragPanelLayout);
        dragPanelLayout.setHorizontalGroup(
            dragPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dragPanelLayout.createSequentialGroup()
                .addComponent(dragBox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnMinimize)
                .addGap(1, 1, 1)
                .addComponent(btnExit))
        );
        dragPanelLayout.setVerticalGroup(
            dragPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dragPanelLayout.createSequentialGroup()
                .addGroup(dragPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(dragBox, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnMinimize, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnExit, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        getContentPane().add(dragPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 960, 36));

        panelWindows.setMaximumSize(new java.awt.Dimension(960, 560));
        panelWindows.setLayout(new java.awt.CardLayout());

        PanelStart.setMaximumSize(new java.awt.Dimension(960, 560));
        PanelStart.setMinimumSize(new java.awt.Dimension(960, 560));
        PanelStart.setPreferredSize(new java.awt.Dimension(960, 560));
        PanelStart.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                PanelStartComponentShown(evt);
            }
        });
        PanelStart.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblHighScore.setFont(new java.awt.Font("Roboto Black", 0, 36)); // NOI18N
        lblHighScore.setForeground(new java.awt.Color(255, 255, 255));
        lblHighScore.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        PanelStart.add(lblHighScore, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 960, 50));

        title.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/iconTitle.png"))); // NOI18N
        title.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        PanelStart.add(title, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 90, 730, 180));

        btnStart.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/iconStart.png"))); // NOI18N
        btnStart.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        PanelStart.add(btnStart, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 320, 460, 70));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/mainBg.png"))); // NOI18N
        PanelStart.add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 960, 560));

        panelWindows.add(PanelStart, "card2");

        getContentPane().add(panelWindows, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 36, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void PanelStartComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_PanelStartComponentShown
        //adds the highscore
        
        if (snakeBoard.highScore != 0){
            lblHighScore.setText("Your Highest Score: " + snakeBoard.highScore);
        }
        
    }//GEN-LAST:event_PanelStartComponentShown

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelStart;
    private javax.swing.JLabel background;
    private javax.swing.JLabel btnExit;
    private javax.swing.JLabel btnMinimize;
    private javax.swing.JLabel btnStart;
    private javax.swing.JPanel dragBox;
    private javax.swing.JPanel dragPanel;
    private javax.swing.JLabel lblHighScore;
    private javax.swing.JPanel panelWindows;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables
    
    private void loadImages() {
        iconStartH = loadImage("iconStartH");
        iconStart = loadImage("iconStart");
        iconExit = loadImage("iconExit");
        iconExitH = loadImage("iconExitH");
        iconMinimize = loadImage("iconMinimize");
        iconMinimizeH = loadImage("iconMinimizeH");
        iconDifficulty= loadImage("iconDifficulty");
        iconDifficultyH = loadImage("iconDifficultyH");
    }
    
    private ImageIcon loadImage(String imageName){
        ImageIcon image = new ImageIcon(getClass().getResource("/images/" + imageName + ".png"));
        return image;
    }
    
    private void loadListeners() {
        
        btnStart.addMouseListener(new MouseAdapter() {
            public void mousePressed(MouseEvent e) {
                //Show the name panel
                
                snakeBoard.resetGame();
                cardLayout.show(panelWindows, "card3");
            }
            public void mouseEntered(MouseEvent e) {
                //hover action
                btnStart.setIcon(iconStartH);
            }
            public void mouseExited(MouseEvent e) {
                //hover exit
                btnStart.setIcon(iconStart);
            }
        });
        
        
        btnExit.addMouseListener(new MouseAdapter() {
            public void mousePressed(MouseEvent e) {
                System.exit(0);
            }
            public void mouseEntered(MouseEvent e) {
                //hover action
                btnExit.setIcon(iconExitH);
            }
            public void mouseExited(MouseEvent e) {
                //hover exit
                btnExit.setIcon(iconExit);
            }
        });
        
        btnMinimize.addMouseListener(new MouseAdapter() {
            public void mousePressed(MouseEvent e) {
                setExtendedState(1);
            }
            public void mouseEntered(MouseEvent e) {
                //hover action
                btnMinimize.setIcon(iconMinimizeH);
            }
            public void mouseExited(MouseEvent e) {
                //hover exit
                btnMinimize.setIcon(iconMinimize);
            }
        });
        
        //---DRAG PANEL---
        dragXPos = -1;
        dragYPos = -1;
        dragPanel.addMouseMotionListener(new MouseMotionAdapter(){
            public void mouseDragged(MouseEvent e) {
                if (dragXPos == -1) {
                    dragXPos = e.getX();
                }
                if (dragYPos == -1) {
                    dragYPos = e.getY();
                }
                setLocation(e.getXOnScreen() - dragXPos, e.getYOnScreen() - dragYPos);
            }});
        
        dragPanel.addMouseListener(new MouseAdapter(){
            //Clears the mouse drag position
            public void mouseReleased(MouseEvent e) {
                dragXPos = -1;
                dragYPos = -1;
            }
        });
        
    }
    
}
